name: Build and Publish

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.02rc
          release_name: Release 1.0.02rc ${{ github.run_number }}

      - name: Upload APK
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: 1.0.02rc.apk
          asset_content_type: application/vnd.android.package-archive


#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: 1.0.01rc.apk
#          path: app/build/outputs/apk/debug/app-debug.apk


#  publish:
#    name: Create Release
#    runs-on: ubuntu-latest
#
#    needs: build
#
#    steps:
#      - name: Upload release APK
#        uses: softprops/action-gh-release@v1
#        with:
#          files: app/build/outputs/apk/release/app-release.apk
#          name: Dummy Release
#          tag_name: 1.0.01rc
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

